manager:
  collectorImage:
    repository: otel/opentelemetry-collector-contrib
  autoInstrumentationImage:
    go:
      repository: ghcr.io/open-telemetry/opentelemetry-go-instrumentation/autoinstrumentation-go
  env:
    - name: ENABLE_GO_AUTO_INSTRUMENTATION
      value: "true"
