config:
  registries:
    - name: GitHub Container Registry
      prefix: ghcr.io
      api_url: https://ghcr.io
      credentials: secret:argocd/ghcr-credentials#token
      defaultns: library
      insecure: false

authScripts:
  enabled: false

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
