config:
  logLevel: debug
  registries:
    - name: GitHub Container Registry
      prefix: ghcr.io
      api_url: https://ghcr.io
      credentials: secret:argocd/ghcr-credentials#token
      defaultns: library
      insecure: false

gitCommit:
  email: image-updater@github.com
  username: gbmoraes-dev

metrics:
  enabled: true
  serviceMonitor:
    enabled: true

extraEnv:
  - name: METRICS_SECURE
    value: "false"
