apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet

metadata:
  name: app-of-apps
  namespace: argocd

spec:
  generators:
    - git:
        repoURL: https://github.com/gbmoraes-dev/blueprint
        revision: main
        directories:
          - path: infra/k8s/argocd/apps/infra/*
          - path: infra/k8s/argocd/apps/services/*
  template:
    metadata:
      name: "{{path.basename}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/gbmoraes-dev/blueprint
        targetRevision: main
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
