apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: go
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
    argocd-image-updater.argoproj.io/image-list: go=ghcr.io/gbmoraes-dev/blueprint-go
    argocd-image-updater.argoproj.io/go.update-strategy: digest
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/write-back-target: "kustomization"
    argocd-image-updater.argoproj.io/git-repository: "https://github.com/gbmoraes-dev/blueprint"

spec:
  project: default
  source:
    repoURL: https://github.com/gbmoraes-dev/blueprint
    targetRevision: main
    path: infra/k8s/services/go/overlays/local
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
